import { Syne, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
  display: "swap",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${syne.variable} ${robotoMono.variable} antialiased h-full px-12 py-8 m-4 border`}
      >
        {children}
        <Footer/>
      </body>
    </html>
  );
}
